### PR TITLE
Add Location Command Line Argument

### PR DESCRIPTION
**Pull request by bacco007**
Add Location Command Line argument, allows Coverage Pattern / Contacts by Distance graphs

### CODE REVIEW

**Comment by mikenye** [comment]
Hi @bacco007,

Thanks for your PR. I will merge this. 

Maybe it's not clear in the Readme, but the intention is for users to add whatever ModeSMixer2 command line arguments they need for their environment/purpose.

Cheers!

**Comment by mikenye** [comment]
In the `docker run` section, could you fix the line continuation backslashes?

Thanks!

**Review by mikenye — CHANGES_REQUESTED** [review]
Can you please fix the line continuation backslashes in the docker run section please?

**Comment by bacco007** [comment]
Done

**Review by mikenye — APPROVED** [review]

**Comment by mikenye** [comment]
Awesome, thanks for this.

**Pull request merged**
